name: Automated Testing
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        BROWSERSTACK_APP_ID: ${{ secrets.BROWSERSTACK_APP_ID }}